name: Add iOS to supportedPlatforms

on:
  # push:
  #   branches:
  #     - gh-on/off-nft-swap-demo
  workflow_dispatch:

jobs:
  add_ios:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Read and Modify supportedPlatforms in JSON files
        id: modify_json
        shell: python
        run: |
          import json
          import os

          file_paths = [
              'dapp_store/zkevm-nft.json',
              'dapp_store/zkevm-swap-info.json',
              'dapp_store/zkevm-swap.json'
          ]
          modified_files_content = {}

          for file_path in file_paths:
            if not os.path.exists(file_path):
              print(f"Error: File not found at {file_path}")
              continue

            try:
              with open(file_path, 'r') as f:
                data = json.load(f)
            except json.JSONDecodeError as e:
              print(f"Error decoding JSON in {file_path}: {e}")
              continue

            modified = False
            if "app" in data and "supportedPlatforms" in data["app"]:
              if "iOS" not in data["app"]["supportedPlatforms"]:
                data["app"]["supportedPlatforms"].append("iOS")
                print(f"'iOS' added to supportedPlatforms in {file_path}")
                modified = True

            if modified:
              try:
                with open(file_path, 'w', encoding='utf-8') as f:
                  json.dump(data, f, indent=2, ensure_ascii=False)
                print(f"{file_path} updated with original characters.")
                with open(file_path, 'r', encoding='utf-8') as f:
                  modified_files_content[file_path] = f.read()
              except IOError as e:
                print(f"Error writing to {file_path}: {e}")
            else:
              print(f"'iOS' already present in supportedPlatforms in {file_path}, skipping.")

          print(f"::set-output name=modified_json_content::{json.dumps(modified_files_content)}")

      # - name: Print Modified JSON Content
      #   if: steps.modify_json.outputs.modified_json_content != '{}'
      #   run: |
      #     import json
      #     modified_content = json.loads('${{ steps.modify_json.outputs.modified_json_content }}')
      #     echo "--- Modified JSON Content ---"
      #     for file, content in modified_content.items():
      #       echo "File: $file"
      #       echo "$content"
      #       echo "---"

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add iOS to supportedPlatforms in JSON files"
          push_options: "" # Removed --force, consider your branching strategy
          file_pattern: "dapp_store/*.json"
          branch: main
          repository: .