name: Toggle iOS Support

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: "Choose operation"
        required: true
        options:
          - add
          - remove

jobs:
  toggle_ios:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Read and Modify supportedPlatforms in JSON files
        id: modify_json
        shell: python
        run: |
          import json
          import os
          import sys

          operation = "${{ github.event.inputs.operation }}"
          file_paths = [
              'dapp_store/zkevm-nft.json',
              'dapp_store/zkevm-swap-info.json',
              'dapp_store/zkevm-swap.json'
          ]
          modified_files_content = {}

          for file_path in file_paths:
            if not os.path.exists(file_path):
              print(f"Error: File not found at {file_path}")
              continue

            try:
              with open(file_path, 'r') as f:
                data = json.load(f)
            except json.JSONDecodeError as e:
              print(f"Error decoding JSON in {file_path}: {e}")
              continue

            modified = False
            if "app" in data and "supportedPlatforms" in data["app"]:
              supported_platforms = data["app"]["supportedPlatforms"]
              if operation == "add":
                if "iOS" not in supported_platforms:
                  supported_platforms.append("iOS")
                  print(f"'iOS' added to supportedPlatforms in {file_path}")
                  modified = True
                else:
                  print(f"'iOS' already present in supportedPlatforms in {file_path}, skipping.")
              elif operation == "remove":
                if "iOS" in supported_platforms:
                  supported_platforms[:] = [platform for platform in supported_platforms if platform != "iOS"]
                  print(f"'iOS' removed from supportedPlatforms in {file_path}")
                  modified = True
                else:
                  print(f"'iOS' not found in supportedPlatforms in {file_path}, skipping.")

            if modified:
              try:
                with open(file_path, 'w', encoding='utf-8') as f:
                  json.dump(data, f, indent=2, ensure_ascii=False)
                print(f"{file_path} updated.")
                with open(file_path, 'r', encoding='utf-8') as f:
                  modified_files_content[file_path] = f.read()
              except IOError as e:
                print(f"Error writing to {file_path}: {e}")

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Toggle iOS support in JSON files"
          push_options: ""
          file_pattern: "dapp_store/*.json"
          branch: gh-on/off-nft-swap-demo
          repository: .
